### ISSUE TITLE
第5章でエラーが出てしまいます

### ISSUE THREAD

**Issue by yoshixile0321** [sikkimtemi/alexa_skill_with_gpt#1]
書籍購入しました。
第3章まで進んで問題はなく、第4章を元にして第5章をこちらのコードをそのまま使用して、
設定しましたが、テストで「〇〇を開いて」で、「私はAIチャットボットです・・・・・」といった返答は
返ってきてますが、そのあとさらに会話をすると、「すみません、エラーが発生しました。しばらく・・・・・」と
なってしまいます。
おそらくAPI呼び出しの部分でエラーとなってる気がしますが、
こちらのソースコードはまだそのまま使えるでしょうか？
もしくは、Consoleエラーがどこに表示されるかがわかるといいのですが。

Chapter05/python
の2種類を使っています。

**Comment by sikkimtemi** [comment]
@yoshixile0321 
ご購入いただき、ありがとうございます。
問題を切り分けるため、次の操作を試していただけますか。

1. スキルの作成でホスティングサービスにPythonを選んで「テンプレート」まで進み、「スキルをインポート」をクリックする。
2. インポート先に https://github.com/sikkimtemi/alexa_skill_chatbot_sample を入力し、インポートする。
3.  「スキルのビルド」で 呼び出し名を適当な名前（「音声チャット」など）に変更し、ビルドする。
5. コードエディタを開いて、'your-api-key'を実際ののAPIキーで置き換えてデプロイする。
6. 「テスト」を開いて、ステータスを「開発中」に変更する。

手順2でインポートするのは、5章のコードに[こちらの記事](https://zenn.dev/sikkim/articles/a3f6633428998e)の対策を追加し、インポート可能な形式に調整したものです。
この手順では、本の中で手動で実施していた設定の大部分が自動で行われるため、オペレーションミスによるエラーが発生しにくくなります。

先ほど動作確認したところ、問題なく動いていたので、コード自体は有効です。
もし上記の手順でもエラーが発生する場合は、OpenAIのAPIキーが失効していないかどうかご確認ください。

**Comment by yoshixile0321** [comment]
ご丁寧にありがとうございます。
解決しました。
頂いたインポートはなぜか一度失敗しましたが、エラー判定していただいていたため特定もしやすく、
予想していたとおりAPIキー周りでした。
エラーが起きた時の確認をもっとしやすくしておこうかなと考えてます。

ご対応ありがとうございました。Alexaスキルはほんとに独特な流れで理解するのが難しく
とても本書が参考になりました。

**Comment by sikkimtemi** [comment]
@yoshixile0321 
解決してよかったです。
また、参考になったと言っていただいて、大変嬉しいです。

**Comment by sikkimtemi** [comment]
closed
